#spring.application.name=lostarkApiCallBatchService
service: LOAC-BAT
spring:
  application:
    name: lostarkApiCallBatchService
  config:
    import: api-domain.yml
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}

  datasource:
    url: jdbc:mysql://localhost:3306/lostarkDB?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&useSSL=false
    username: ${database.user}
    password: ${database.password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  sql:
    init:
      mode: always
      schema-locations: classpath:sql/batch-schema-mysql.sql

  batch:
    jdbc:
      initialize-schema: always  # Spring Batch 테이블 자동 생성
      schema: classpath:org/springframework/batch/core/schema-mysql.sql
    job:
      enabled: false # 스케줄러로 관리하므로 자동 실행 비활성화


# Logback 설정은 logback-spring.xml에서 관리
logging:
  config: classpath:logback-spring.xml

# 서버 포트 설정
server:
  port: 8080

# Management endpoints 설정 (Spring Boot Actuator)
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
      base-path: /actuator
  endpoint:
    health:
      show-details: always