#spring.application.name=lostarkApiCallBatchService
spring:
  application:
    name: lostarkApiCallBatchService
  config:
    import: api-domain.yml, jwt.yml
logging:
  level:
    root: info
    org.springframework.web: info
    org.springframework.web.client.RestTemplate: DEBUG
    com.laapicallbat.lostarkapicallbatchservice.aa.customclass.MyRestTemplate: DEBUG
    com.laapicallbat.lostarkapicallbatchservice.biz: DEBUG
    com.laapicallbat.lostarkapicallbatchservice.aa: debug
    org.junit: debug
    org.springframework.test: debug
#  pattern:
#    console: "{%thread}[%p](%C-%M)%d{yyyy-MM-dd HH:mm:ss} - %msg%n"



