#spring.application.name=lostarkApiCallBatchService
service: LOAC-BAT
spring:
  application:
    name: lostarkApiCallBatchService
  config:
    import: api-domain.yml

  datasource:
    url: jdbc:mysql://localhost:3306/lostarkDB?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${database.user}
    password: ${database.password}
    driver-class-name: com.mysql.cj.jdbc.Driver
logging:
  level:
    root: info
    org.springframework.web: info
    org.springframework.web.client.RestTemplate: DEBUG
    com.laapicallbat.lostarkapicallbatchservice.aa.customclass.MyRestTemplate: DEBUG
    com.laapicallbat.lostarkapicallbatchservice.biz: DEBUG
    com.laapicallbat.lostarkapicallbatchservice.aa: debug
    org.junit: debug
    org.springframework.test: debug
    com.laapicallbat.lostarkapicallbatchservice.config: DEBUG
#  pattern:
#    console: '{%thread}[%p](%C-%M)%d{yyyy-MM-dd HH:mm:ss} - %msg%n"



